name: Build and Push Docker Image

on:
  push:
    branches: [ docker-main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List files in current directory
      run: ls -al  
      
    - name: Build and push Docker image
      run: |
        docker-compose up -d  
        docker-compose push    